//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.PurchaseOrderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseOrderFilterDTO", Namespace="http://schemas.datacontract.org/2004/07/DataContracts")]
    [System.SerializableAttribute()]
    public partial class PurchaseOrderFilterDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SkipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TakeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserRoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Skip {
            get {
                return this.SkipField;
            }
            set {
                if ((this.SkipField.Equals(value) != true)) {
                    this.SkipField = value;
                    this.RaisePropertyChanged("Skip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Take {
            get {
                return this.TakeField;
            }
            set {
                if ((this.TakeField.Equals(value) != true)) {
                    this.TakeField = value;
                    this.RaisePropertyChanged("Take");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserRole {
            get {
                return this.UserRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRoleField, value) != true)) {
                    this.UserRoleField = value;
                    this.RaisePropertyChanged("UserRole");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseOrdersHeaderDTO", Namespace="http://schemas.datacontract.org/2004/07/DataContracts")]
    [System.SerializableAttribute()]
    public partial class PurchaseOrdersHeaderDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FreightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PurchaseOrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ShipDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShipMethodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipMethodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SubTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TaxAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalDueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeFullName {
            get {
                return this.EmployeeFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeFullNameField, value) != true)) {
                    this.EmployeeFullNameField = value;
                    this.RaisePropertyChanged("EmployeeFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Freight {
            get {
                return this.FreightField;
            }
            set {
                if ((this.FreightField.Equals(value) != true)) {
                    this.FreightField = value;
                    this.RaisePropertyChanged("Freight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PurchaseOrderID {
            get {
                return this.PurchaseOrderIDField;
            }
            set {
                if ((this.PurchaseOrderIDField.Equals(value) != true)) {
                    this.PurchaseOrderIDField = value;
                    this.RaisePropertyChanged("PurchaseOrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShipDate {
            get {
                return this.ShipDateField;
            }
            set {
                if ((this.ShipDateField.Equals(value) != true)) {
                    this.ShipDateField = value;
                    this.RaisePropertyChanged("ShipDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShipMethodID {
            get {
                return this.ShipMethodIDField;
            }
            set {
                if ((this.ShipMethodIDField.Equals(value) != true)) {
                    this.ShipMethodIDField = value;
                    this.RaisePropertyChanged("ShipMethodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipMethodName {
            get {
                return this.ShipMethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipMethodNameField, value) != true)) {
                    this.ShipMethodNameField = value;
                    this.RaisePropertyChanged("ShipMethodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusName {
            get {
                return this.StatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNameField, value) != true)) {
                    this.StatusNameField = value;
                    this.RaisePropertyChanged("StatusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SubTotal {
            get {
                return this.SubTotalField;
            }
            set {
                if ((this.SubTotalField.Equals(value) != true)) {
                    this.SubTotalField = value;
                    this.RaisePropertyChanged("SubTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxAmt {
            get {
                return this.TaxAmtField;
            }
            set {
                if ((this.TaxAmtField.Equals(value) != true)) {
                    this.TaxAmtField = value;
                    this.RaisePropertyChanged("TaxAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDue {
            get {
                return this.TotalDueField;
            }
            set {
                if ((this.TotalDueField.Equals(value) != true)) {
                    this.TotalDueField = value;
                    this.RaisePropertyChanged("TotalDue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseOrderDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/DataContracts")]
    [System.SerializableAttribute()]
    public partial class PurchaseOrderDetailDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.PurchaseOrderServiceReference.PurchaseOrderDetailRowDTO[] PurchaseDetailRowDTOsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.PurchaseOrderServiceReference.PurchaseOrdersHeaderDTO PurchaseOrdersDTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.PurchaseOrderServiceReference.PurchaseOrderDetailRowDTO[] PurchaseDetailRowDTOs {
            get {
                return this.PurchaseDetailRowDTOsField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchaseDetailRowDTOsField, value) != true)) {
                    this.PurchaseDetailRowDTOsField = value;
                    this.RaisePropertyChanged("PurchaseDetailRowDTOs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.PurchaseOrderServiceReference.PurchaseOrdersHeaderDTO PurchaseOrdersDTO {
            get {
                return this.PurchaseOrdersDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchaseOrdersDTOField, value) != true)) {
                    this.PurchaseOrdersDTOField = value;
                    this.RaisePropertyChanged("PurchaseOrdersDTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseOrderDetailRowDTO", Namespace="http://schemas.datacontract.org/2004/07/DataContracts")]
    [System.SerializableAttribute()]
    public partial class PurchaseOrderDetailRowDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LineTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short OrderQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PurchaseOrderDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PurchaseOrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ReceivedQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RejectedQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal StockedQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LineTotal {
            get {
                return this.LineTotalField;
            }
            set {
                if ((this.LineTotalField.Equals(value) != true)) {
                    this.LineTotalField = value;
                    this.RaisePropertyChanged("LineTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short OrderQty {
            get {
                return this.OrderQtyField;
            }
            set {
                if ((this.OrderQtyField.Equals(value) != true)) {
                    this.OrderQtyField = value;
                    this.RaisePropertyChanged("OrderQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PurchaseOrderDetailID {
            get {
                return this.PurchaseOrderDetailIDField;
            }
            set {
                if ((this.PurchaseOrderDetailIDField.Equals(value) != true)) {
                    this.PurchaseOrderDetailIDField = value;
                    this.RaisePropertyChanged("PurchaseOrderDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PurchaseOrderID {
            get {
                return this.PurchaseOrderIDField;
            }
            set {
                if ((this.PurchaseOrderIDField.Equals(value) != true)) {
                    this.PurchaseOrderIDField = value;
                    this.RaisePropertyChanged("PurchaseOrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReceivedQty {
            get {
                return this.ReceivedQtyField;
            }
            set {
                if ((this.ReceivedQtyField.Equals(value) != true)) {
                    this.ReceivedQtyField = value;
                    this.RaisePropertyChanged("ReceivedQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RejectedQty {
            get {
                return this.RejectedQtyField;
            }
            set {
                if ((this.RejectedQtyField.Equals(value) != true)) {
                    this.RejectedQtyField = value;
                    this.RaisePropertyChanged("RejectedQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StockedQty {
            get {
                return this.StockedQtyField;
            }
            set {
                if ((this.StockedQtyField.Equals(value) != true)) {
                    this.StockedQtyField = value;
                    this.RaisePropertyChanged("StockedQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PurchaseOrderServiceReference.IPurchaseOrderService")]
    public interface IPurchaseOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/GetPurchaseOrderHeadersDTO", ReplyAction="http://tempuri.org/IPurchaseOrderService/GetPurchaseOrderHeadersDTOResponse")]
        Web.PurchaseOrderServiceReference.PurchaseOrdersHeaderDTO[] GetPurchaseOrderHeadersDTO(Web.PurchaseOrderServiceReference.PurchaseOrderFilterDTO purchaseOrderFilterDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/GetPurchaseOrderHeadersDTO", ReplyAction="http://tempuri.org/IPurchaseOrderService/GetPurchaseOrderHeadersDTOResponse")]
        System.Threading.Tasks.Task<Web.PurchaseOrderServiceReference.PurchaseOrdersHeaderDTO[]> GetPurchaseOrderHeadersDTOAsync(Web.PurchaseOrderServiceReference.PurchaseOrderFilterDTO purchaseOrderFilterDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/GetCountOfPurchaseOrderHeaderDTOs", ReplyAction="http://tempuri.org/IPurchaseOrderService/GetCountOfPurchaseOrderHeaderDTOsRespons" +
            "e")]
        int GetCountOfPurchaseOrderHeaderDTOs(Web.PurchaseOrderServiceReference.PurchaseOrderFilterDTO purchaseOrderFilterDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/GetCountOfPurchaseOrderHeaderDTOs", ReplyAction="http://tempuri.org/IPurchaseOrderService/GetCountOfPurchaseOrderHeaderDTOsRespons" +
            "e")]
        System.Threading.Tasks.Task<int> GetCountOfPurchaseOrderHeaderDTOsAsync(Web.PurchaseOrderServiceReference.PurchaseOrderFilterDTO purchaseOrderFilterDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/GetPurchaseOrderDetailDTO", ReplyAction="http://tempuri.org/IPurchaseOrderService/GetPurchaseOrderDetailDTOResponse")]
        Web.PurchaseOrderServiceReference.PurchaseOrderDetailDTO GetPurchaseOrderDetailDTO(System.Guid orderGuidId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/GetPurchaseOrderDetailDTO", ReplyAction="http://tempuri.org/IPurchaseOrderService/GetPurchaseOrderDetailDTOResponse")]
        System.Threading.Tasks.Task<Web.PurchaseOrderServiceReference.PurchaseOrderDetailDTO> GetPurchaseOrderDetailDTOAsync(System.Guid orderGuidId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/Create", ReplyAction="http://tempuri.org/IPurchaseOrderService/CreateResponse")]
        Web.PurchaseOrderServiceReference.PurchaseOrderDetailDTO Create(string cartId, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/Create", ReplyAction="http://tempuri.org/IPurchaseOrderService/CreateResponse")]
        System.Threading.Tasks.Task<Web.PurchaseOrderServiceReference.PurchaseOrderDetailDTO> CreateAsync(string cartId, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/Ship", ReplyAction="http://tempuri.org/IPurchaseOrderService/ShipResponse")]
        void Ship(System.Guid orderGuidId, string managerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/Ship", ReplyAction="http://tempuri.org/IPurchaseOrderService/ShipResponse")]
        System.Threading.Tasks.Task ShipAsync(System.Guid orderGuidId, string managerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/Close", ReplyAction="http://tempuri.org/IPurchaseOrderService/CloseResponse")]
        void Close(System.Guid orderGuidId, string managerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/Close", ReplyAction="http://tempuri.org/IPurchaseOrderService/CloseResponse")]
        System.Threading.Tasks.Task CloseAsync(System.Guid orderGuidId, string managerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchaseOrderServiceChannel : Web.PurchaseOrderServiceReference.IPurchaseOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseOrderServiceClient : System.ServiceModel.ClientBase<Web.PurchaseOrderServiceReference.IPurchaseOrderService>, Web.PurchaseOrderServiceReference.IPurchaseOrderService {
        
        public PurchaseOrderServiceClient() {
        }
        
        public PurchaseOrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseOrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseOrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Web.PurchaseOrderServiceReference.PurchaseOrdersHeaderDTO[] GetPurchaseOrderHeadersDTO(Web.PurchaseOrderServiceReference.PurchaseOrderFilterDTO purchaseOrderFilterDTO) {
            return base.Channel.GetPurchaseOrderHeadersDTO(purchaseOrderFilterDTO);
        }
        
        public System.Threading.Tasks.Task<Web.PurchaseOrderServiceReference.PurchaseOrdersHeaderDTO[]> GetPurchaseOrderHeadersDTOAsync(Web.PurchaseOrderServiceReference.PurchaseOrderFilterDTO purchaseOrderFilterDTO) {
            return base.Channel.GetPurchaseOrderHeadersDTOAsync(purchaseOrderFilterDTO);
        }
        
        public int GetCountOfPurchaseOrderHeaderDTOs(Web.PurchaseOrderServiceReference.PurchaseOrderFilterDTO purchaseOrderFilterDTO) {
            return base.Channel.GetCountOfPurchaseOrderHeaderDTOs(purchaseOrderFilterDTO);
        }
        
        public System.Threading.Tasks.Task<int> GetCountOfPurchaseOrderHeaderDTOsAsync(Web.PurchaseOrderServiceReference.PurchaseOrderFilterDTO purchaseOrderFilterDTO) {
            return base.Channel.GetCountOfPurchaseOrderHeaderDTOsAsync(purchaseOrderFilterDTO);
        }
        
        public Web.PurchaseOrderServiceReference.PurchaseOrderDetailDTO GetPurchaseOrderDetailDTO(System.Guid orderGuidId) {
            return base.Channel.GetPurchaseOrderDetailDTO(orderGuidId);
        }
        
        public System.Threading.Tasks.Task<Web.PurchaseOrderServiceReference.PurchaseOrderDetailDTO> GetPurchaseOrderDetailDTOAsync(System.Guid orderGuidId) {
            return base.Channel.GetPurchaseOrderDetailDTOAsync(orderGuidId);
        }
        
        public Web.PurchaseOrderServiceReference.PurchaseOrderDetailDTO Create(string cartId, string userId) {
            return base.Channel.Create(cartId, userId);
        }
        
        public System.Threading.Tasks.Task<Web.PurchaseOrderServiceReference.PurchaseOrderDetailDTO> CreateAsync(string cartId, string userId) {
            return base.Channel.CreateAsync(cartId, userId);
        }
        
        public void Ship(System.Guid orderGuidId, string managerId) {
            base.Channel.Ship(orderGuidId, managerId);
        }
        
        public System.Threading.Tasks.Task ShipAsync(System.Guid orderGuidId, string managerId) {
            return base.Channel.ShipAsync(orderGuidId, managerId);
        }
        
        public void Close(System.Guid orderGuidId, string managerId) {
            base.Channel.Close(orderGuidId, managerId);
        }
        
        public System.Threading.Tasks.Task CloseAsync(System.Guid orderGuidId, string managerId) {
            return base.Channel.CloseAsync(orderGuidId, managerId);
        }
    }
}
